#!/usr/bin/perl -e$_=$ARGV[0];exec(s|[^/]+$|tarantool|r,@ARGV)
if os.getenv("LOCAL_LUA_DEBUGGER_VSCODE") == "1" then
    require 'strict'.off() -- FIXME
    require 'lldebugger'.start()
end
dofile(unpack(arg));
os.exit(0)
